version: '3.8'
services:
  # add the dajngo api service
  api:
    build:
      context: ./api
    container_name: django-dev
    environment:
      - MONGO_DB_URI
      - ORGANIZATION
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
    working_dir: /api
    command: python manage.py runserver
    
  app:
    build:
      context: ./app
    container_name: angular-dev
    ports:
      - 4200:4200
    volumes:
      - ./app:/app
      - /app/node_modules  # separate volume for node_modules to avoid unnecessary npm installs
    working_dir: /app
    command: npm start -- --host 0.0.0.0 # allow access from outside the container
